apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-dep
  labels:
    app: dev
    env: mydev

spec:
  replicas: 5

  selector:
    matchLabels:
      app: dev
      env: mydev

  template:
    metadata:
      labels:
        app: dev
        env: mydev

    spec:
      containers:
        - name: nginx
          image: babugyadav/nginx:{{ .Values.image.tag }}
          ports:
            - containerPort: 80