# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: production

replicaCount: 4

image:
<<<<<<< HEAD
  repository: nginx
<<<<<<< HEAD
  tag: "30822346386"
=======
<<<<<<< HEAD
  tag: "30822346386"
=======
  tag: "30822346386"
>>>>>>> 9a5448473de74be9ea2535cfd88af2a91f2224fe
>>>>>>> 3ae25c9b46dfd9bbdcdb7e33bc667e907e9c5de9
  pullPolicy: Always
=======
  repository: babugyadav/nginx
  tag: "v1"

>>>>>>> f7b4ed6 (babug)

env:
  name: ENV
  value: production

service:
  name: nginx-service
  type: NodePort
  port: 80
  targetPort: 80
