# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
env: prod
app: dev
images:
  repository: babugyadav/nginx
  tag: "30885447988"




