# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: babugyadav/nginx
  tag: "30836197472"

replicaCount: 5

env: mydev

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080


