update-newtag-in-helm-chart:
  runs-on: ubuntu-latest
  needs: build

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ github.token }}

    - name: Check repository files
      run: |
        pwd
        ls -la
        find . -type f -name "values.yaml"

    - name: Update tag in Helm chart
      run: |
        sed -i 's/^[[:space:]]*tag:.*/  tag: "${{ github.run_id }}"/' project/values.yaml

    - name: Verify tag update
      run: |
        cat project/values.yaml
        grep -n "tag" project/values.yaml
        git diff project/values.yaml

    - name: Commit and push changes
      run: |
        git config --global user.email "babusuccess@gmail.com"
        git config --global user.name "babusuccess"

        git add project/values.yaml

        git commit -m "Update tag in Helm chart" || echo "No changes to commit"

        git pull --rebase origin main

        git push origin main
